<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--Explicit import Directory.Build.props (for old-style csproj)-->
  <Import Project="..\Directory.Build.props" Condition="'$(UsingMicrosoftNETSdk)' != 'true'" />
  
  <Import Project="$(SlnDir)\UsedPackages.version" />
  <ItemGroup Condition="'$(TargetFramework)'!='net462'">
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="C:\Repositories\FastReport\FastReport.Compat\shared\WindowsForms\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="C:\Repositories\FastReport\FastReport.Compat\shared\Compiler\VBCodeProvider.cs" />
    <Compile Remove="C:\Repositories\FastReport\FastReport.Compat\shared\DotNetClasses\Color.Full.cs" />
    <Compile Remove="C:\Repositories\FastReport\FastReport.Compat\shared\TypeConverters\SizeConverter.cs" />
  </ItemGroup>
 
  
  <ItemGroup>
    <None Include="$(SourceCode)\DotNetClasses\UITypeEditor.cs">
      <Link>DotNetClasses\UITypeEditor.cs</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <Visible>false</Visible>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
  </ItemGroup>
</Project>